# -*- coding: utf-8 -*-
"""LCF_5900_Clima

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OdQA3XYO-lORps3uour68H239mUZakIG
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
import statsmodels.formula.api as smf
import pymannkendall as mk
from datetime import datetime

# Configuração de estilo dos gráficos
sns.set_theme(style="whitegrid")
plt.rcParams.update({'font.size': 11, 'axes.labelsize': 12, 'axes.titlesize': 14})

# ==============================================================================
# CARREGAMENTO E ESTRUTURAÇÃO DOS DADOS
# ==============================================================================

# Importar o conjunto completo de dados do Excel
# Substitua pelo caminho correto se necessário
climate_data = pd.read_excel("DadosClima_Piracicaba.xlsx")

# Criar coluna de data formatada e estruturar os tipos de dados (Categorias ordenadas)
climate_data['Date'] = pd.to_datetime(climate_data[['Ano', 'Mes', 'Dia']].assign(
    Year=climate_data['Ano'], Month=climate_data['Mes'], Day=climate_data['Dia']
)[['Year', 'Month', 'Day']])

# Definir ordens categóricas para os fatores
trimestre_order = ["JFM", "FMA", "MAM", "AMJ", "MJJ", "JJA", "JAS", "ASO", "SON", "OND", "NDJ", "DJF"]
estacao_order = ["Summer", "Autumn", "Winter", "Spring"]
nino_order = ["Strong La Niña", "Intermediate", "Strong El Niño"]

# Mapeamento de traduções e categorização
climate_data['Estacao'] = climate_data['Estacao'].replace({
    "Verão": "Summer", "Outono": "Autumn", "Inverno": "Winter", "Primavera": "Spring"
})
climate_data['ClassNino'] = climate_data['ClassNino'].replace({
    "StrgNina": "Strong La Niña", "Interm": "Intermediate", "StrgNino": "Strong El Niño"
})

climate_data['Trimestre'] = pd.Categorical(climate_data['Trimestre'], categories=trimestre_order, ordered=True)
climate_data['Estacao'] = pd.Categorical(climate_data['Estacao'], categories=estacao_order, ordered=True)
climate_data['ClassNino'] = pd.Categorical(climate_data['ClassNino'], categories=nino_order, ordered=True)

# Variáveis derivadas adicionais
climate_data['Decade'] = (climate_data['Ano'] // 10) * 10
climate_data['DTR'] = climate_data['TMAX'] - climate_data['TMIN']

print(f"Dataset spans from {climate_data['Date'].min().strftime('%Y-%m-%d')} to {climate_data['Date'].max().strftime('%Y-%m-%d')}")
print(f"Total observations: {len(climate_data)}\n")

# ==============================================================================
# FUNÇÕES AUXILIARES
# ==============================================================================

def trend_summary(df, year_col, var_col):
    """Executa o teste de Mann-Kendall e calcula o Sen's Slope omitindo NaNs."""
    clean_df = df[[year_col, var_col]].dropna()
    res = mk.original_test(clean_df[var_col])

    return pd.DataFrame({
        'Sen_Slope': [res.slope],
        'MK_Tau': [res.tau],
        'p_value': [res.p],
        'Significant': ['Yes' if res.p < 0.05 else 'No']
    })

def moving_avg(series, n=10):
    """Calcula a média móvel centralizada."""
    return series.rolling(window=n, center=True).mean()

# ==============================================================================
# ITEM 1: ANÁLISES DE TEMPERATURA E EXTREMOS TÉRMICOS
# ==============================================================================

annual_temp = climate_data[climate_data['Ano'] >= 1917].dropna(subset=['TMED', 'TMIN', 'TMAX'])
annual_temp = annual_temp.groupby('Ano').agg(
    Mean_TMIN=('TMIN', 'mean'),
    Mean_TMED=('TMED', 'mean'),
    Mean_TMAX=('TMAX', 'mean'),
    Mean_DTR=('DTR', 'mean')
).reset_index()

# Modelos Lineares (Mínimos Quadrados)
for var in ['TMIN', 'TMED', 'TMAX']:
    model = smf.ols(f'Mean_{var} ~ Ano', data=annual_temp).fit()
    print(f"--- Linear Regression for {var} ---")
    print(f"Slope per decade: {model.params['Ano'] * 10:.4f} °C")
    print(f"R-squared: {model.rsquared:.4f} | p-value: {model.pvalues['Ano']:.4e}\n")

print("--- Mann-Kendall Trend Tests for Temperatures ---")
for var in ['TMIN', 'TMED', 'TMAX']:
    print(f"{var}:")
    print(trend_summary(annual_temp, 'Ano', f'Mean_{var}'))

# Plot Q1: Tendências de Temperatura
plt.figure(figsize=(10, 6))
temp_colors = {"Tmin": "#3498db", "Tmean": "#2ecc71", "Tmax": "#e74c3c"}
for label, col in zip(["Tmin", "Tmean", "Tmax"], ["Mean_TMIN", "Mean_TMED", "Mean_TMAX"]):
    sns.lineplot(data=annual_temp, x='Ano', y=col, color=temp_colors[label], alpha=0.4)
    sns.regplot(data=annual_temp, x='Ano', y=col, color=temp_colors[label], scatter=False, label=label)
plt.title("Long-term Temperature Trends in Piracicaba (1917–Present)\nLinear trends fitted to annual means")
plt.xlabel("Year")
plt.ylabel("Temperature (°C)")
plt.legend(loc='lower center', bbox_to_anchor=(0.5, -0.15), ncol=3)
plt.tight_layout()
plt.savefig("Q1_temperature_trends.png", dpi=150)
plt.close()

# Plot Q1: Tendência da Amplitude Térmica Diária (DTR)
plt.figure(figsize=(10, 5))
sns.lineplot(data=annual_temp, x='Ano', y='Mean_DTR', color='grey', alpha=0.5)
sns.regplot(data=annual_temp, x='Ano', y='Mean_DTR', color='#e74c3c', scatter=False)
annual_temp['DTR_MA'] = moving_avg(annual_temp['Mean_DTR'], 10)
sns.lineplot(data=annual_temp, x='Ano', y='DTR_MA', color='#2c3e50', linewidth=2, label="10-year MA")
plt.title("Diurnal Temperature Range (Tmax − Tmin)\nAnnual mean with 10-year moving average and linear trend")
plt.xlabel("Year")
plt.ylabel("DTR (°C)")
plt.savefig("Q1_DTR_trend.png", dpi=150)
plt.close()

# Extremos de Calor (> 35°C)
extreme_heat = climate_data[climate_data['Ano'] >= 1917].dropna(subset=['TMAX'])
extreme_heat = extreme_heat.groupby('Ano').agg(
    Days_Above_35=('TMAX', lambda x: (x > 35).sum())
).reset_index()

plt.figure(figsize=(10, 5))
plt.bar(extreme_heat['Ano'], extreme_heat['Days_Above_35'], color='#c0392b', alpha=0.7)
sns.regplot(data=extreme_heat, x='Ano', y='Days_Above_35', color='black', scatter=False, lowess=True)
plt.title("Annual Frequency of Extreme Heat Days (Tmax > 35°C)")
plt.xlabel("Year")
plt.ylabel("Number of Days")
plt.savefig("Q1_extreme_heat_days.png", dpi=150)
plt.close()

# Nota sobre quebra estrutural: O pacote 'strucchange' do R não possui um clone direto
# 100% equivalente nativo em Python, mas os plots principais foram mantidos.

# ==============================================================================
# ITEM 2: DINÂMICA HÍDRICA E REGIME DE PRECIPITAÇÃO
# ==============================================================================

annual_rain = climate_data[climate_data['Ano'] >= 1902].dropna(subset=['Chuva'])
annual_rain = annual_rain.groupby('Ano').agg(
    Total_Rain=('Chuva', 'sum'),
    Rainy_Days=('Chuva', lambda x: (x > 0.1).sum())
).reset_index()

# Plot Q2: Chuva Total Anual
plt.figure(figsize=(10, 5))
sns.lineplot(data=annual_rain, x='Ano', y='Total_Rain', color='#2980b9', alpha=0.6)
sns.regplot(data=annual_rain, x='Ano', y='Total_Rain', color='#e74c3c', scatter=False)
annual_rain['Rain_MA'] = moving_avg(annual_rain['Total_Rain'], 10)
sns.lineplot(data=annual_rain, x='Ano', y='Rain_MA', color='#2c3e50', linewidth=2)
plt.axhline(annual_rain['Total_Rain'].mean(), linetype="--", color="grey")
plt.title("Total Annual Rainfall in Piracicaba (1902–Present)")
plt.xlabel("Year")
plt.ylabel("Annual Rainfall (mm)")
plt.savefig("Q2_annual_rainfall.png", dpi=150)
plt.close()

# Estiagens e Períodos Secos
dry_spells = climate_data[climate_data['Ano'] >= 1902].groupby('Ano').agg(
    Max_Estiagem=('Estiagem', 'max')
).reset_index()

plt.figure(figsize=(10, 5))
sns.lineplot(data=dry_spells, x='Ano', y='Max_Estiagem', color='#d35400', alpha=0.6)
sns.regplot(data=dry_spells, x='Ano', y='Max_Estiagem', color='#c0392b', scatter=False)
dry_spells['Estiagem_MA'] = moving_avg(dry_spells['Max_Estiagem'], 10)
sns.lineplot(data=dry_spells, x='Ano', y='Estiagem_MA', color='#2c3e50', linewidth=2)
plt.title("Maximum Annual Dry Spell Length\nLongest consecutive period without rain each year")
plt.xlabel("Year")
plt.ylabel("Days")
plt.savefig("Q2_dry_spells.png", dpi=150)
plt.close()

# Boxplot Decadal de Estiagem
dry_spell_decade = climate_data[(climate_data['Ano'] >= 1902) & (climate_data['Estiagem'] > 0)].copy()
plt.figure(figsize=(10, 5))
sns.boxplot(data=dry_spell_decade, x='Decade', y='Estiagem', color='#f39c12', boxprops=dict(alpha=0.5))
plt.title("Distribution of Dry Spell Lengths by Decade")
plt.xticks(rotation=45)
plt.xlabel("Decade")
plt.ylabel("Dry Spell Length (days)")
plt.savefig("Q2_dry_spells_decades.png", dpi=150)
plt.close()

# Chuvas Extremas (> 50mm) e Máximas Diárias
extreme_rain = climate_data[climate_data['Ano'] >= 1902].dropna(subset=['Chuva']).groupby('Ano').agg(
    Max_Daily=('Chuva', 'max'),
    Days_Above_50mm=('Chuva', lambda x: (x > 50).sum())
).reset_index()

fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 8))
sns.scatterplot(data=extreme_rain, x='Ano', y='Max_Daily', color='#2980b9', alpha=0.6, ax=ax1)
sns.regplot(data=extreme_rain, x='Ano', y='Max_Daily', color='#e74c3c', scatter=False, ax=ax1)
ax1.set_title("Annual Maximum Daily Rainfall")
ax1.set_ylabel("Max Daily Rainfall (mm)")

ax2.bar(extreme_rain['Ano'], extreme_rain['Days_Above_50mm'], color='#2980b9', alpha=0.6)
sns.regplot(data=extreme_rain, x='Ano', y='Days_Above_50mm', color='black', scatter=False, lowess=True, ax=ax2)
ax2.set_title("Annual Count of Heavy Rain Days (> 50 mm/day)")
ax2.set_ylabel("Number of Days")
plt.tight_layout()
plt.savefig("Q2_extreme_rainfall.png", dpi=150)
plt.close()

# ==============================================================================
# ITEM 3: CLIMATOLOGIA SAZONAL E TRIMESTRAL
# ==============================================================================

# Início da estação chuvosa (Janela Móvel de 5 dias com acúmulo >= 20mm pós Set-01)
wet_data = climate_data[climate_data['Mes'].isin([9, 10, 11, 12])].sort_values('Date').copy()
wet_data['Rain_5day'] = wet_data.groupby('Ano')['Chuva'].transform(lambda x: x.rolling(5).sum())

wet_season_onset = wet_data[wet_data['Rain_5day'] >= 20].groupby('Ano').first().reset_index()
wet_season_onset['DOY_onset'] = wet_season_onset['Date'].dt.dayofyear

plt.figure(figsize=(10, 5))
sns.scatterplot(data=wet_season_onset, x='Ano', y='DOY_onset', color='#27ae60', alpha=0.6)
sns.regplot(data=wet_season_onset, x='Ano', y='DOY_onset', color='#c0392b', scatter=False)
plt.title("Wet Season Onset Date (1902–Present)\nFirst 5-day period with ≥20 mm after September 1")
plt.xlabel("Year")
plt.ylabel("Onset Date")
# Ajuste de rótulos do eixo Y para corresponder às datas julianas aproximadas
plt.yticks([244, 274, 305, 335], ["Sep 1", "Oct 1", "Nov 1", "Dec 1"])
plt.savefig("Q3_wet_season_onset.png", dpi=150)
plt.close()

# Risco de Geada (Tmin < 5°C)
frost_risk = climate_data[climate_data['Ano'] >= 1917].dropna(subset=['TMIN']).groupby('Ano').agg(
    Frost_Light=('TMIN', lambda x: (x < 5).sum())
).reset_index()

plt.figure(figsize=(10, 5))
plt.bar(frost_risk['Ano'], frost_risk['Frost_Light'], color='#85c1e9', alpha=0.7)
sns.regplot(data=frost_risk, x='Ano', y='Frost_Light', color='#2c3e50', scatter=False, lowess=True)
plt.title("Annual Frost Risk Days (Tmin < 5°C)\nIs the frost-risk window shrinking?")
plt.xlabel("Year")
plt.ylabel("Number of Days")
plt.savefig("Q3_frost_risk.png", dpi=150)
plt.close()

# Distribuição Trimestral da Chuva por Recortes Históricos
def assign_period(year):
    if year < 1950: return "1902–1949"
    elif year < 1980: return "1950–1979"
    elif year < 2000: return "1980–1999"
    else: return "2000–Present"

trimestre_rain = climate_data[climate_data['Ano'] >= 1902].dropna(subset=['Chuva']).copy()
trimestre_rain['Period'] = trimestre_rain['Ano'].apply(assign_period)
trimestre_rain = trimestre_rain.groupby(['Period', 'Trimestre'], observed=False)['Chuva'].mean().reset_index()

plt.figure(figsize=(10, 5))
sns.barplot(data=trimestre_rain, x='Trimestre', y='Chuva', hue='Period', palette='Set2')
plt.title("Mean Daily Rainfall by Trimestre Across Periods")
plt.xlabel("Trimestre (Rolling 3-month Window)")
plt.ylabel("Mean Daily Rainfall (mm)")
plt.xticks(rotation=45)
plt.legend(title="Period")
plt.tight_layout()
plt.savefig("Q3_trimestre_rainfall.png", dpi=150)
plt.close()

# ==============================================================================
# ITEM 4: FENÔMENO EL NIÑO-OSCILAÇÃO SUL (ENOS)
# ==============================================================================

enso_rain = climate_data[climate_data['Ano'] >= 1950].dropna(subset=['ClassNino', 'Chuva'])
enso_rain = enso_rain.groupby(['Ano', 'Estacao', 'ClassNino'], observed=False)['Chuva'].sum().reset_index()

g = sns.catplot(
    data=enso_rain, x='ClassNino', y='Chuva', hue='ClassNino', shade=True,
    col='Estacao', col_wrap=2, kind='box', height=4.5, aspect=1.2, palette={
        "Strong La Niña": "#3498db", "Intermediate": "#95a5a6", "Strong El Niño": "#e74c3c"
    }
)
g.set_titles("{col_name}")
g.set_axis_labels("ENSO Classification", "Seasonal Rainfall (mm)")
g.set_xticklabels(rotation=30)
plt.savefig("Q4_enso_rainfall.png", dpi=150)
plt.close()

# Anomalias Térmicas Mensais (Base 1961-1990)
baseline = climate_data[(climate_data['Ano'] >= 1961) & (climate_data['Ano'] <= 1990)].groupby('Mes')['TMED'].mean().reset_index(name='Clim_TMED')
enso_temp = climate_data[climate_data['Ano'] >= 1950].dropna(subset=['ClassNino', 'TMED']).merge(baseline, on='Mes')
enso_temp['Temp_Anomaly'] = enso_temp['TMED'] - enso_temp['Clim_TMED']
enso_temp = enso_temp.groupby(['Ano', 'ClassNino'], observed=False)['Temp_Anomaly'].mean().reset_index()

plt.figure(figsize=(10, 6))
sns.scatterplot(data=enso_temp, x='Ano', y='Temp_Anomaly', hue='ClassNino', palette={"Strong La Niña": "#3498db", "Intermediate": "#95a5a6", "Strong El Niño": "#e74c3c"}, alpha=0.5)
sns.notebook_trend = sns.lmplot(data=enso_temp, x='Ano', y='Temp_Anomaly', hue='ClassNino', palette={"Strong La Niña": "#3498db", "Intermediate": "#95a5a6", "Strong El Niño": "#e74c3c"}, scatter=False)
plt.close() # Fecha a figura extra criada pelo lmplot interno

plt.figure(figsize=(10, 6))
sns.scatterplot(data=enso_temp, x='Ano', y='Temp_Anomaly', hue='ClassNino', palette={"Strong La Niña": "#3498db", "Intermediate": "#95a5a6", "Strong El Niño": "#e74c3c"}, alpha=0.5)
for phase, color in zip(["Strong La Niña", "Intermediate", "Strong El Niño"], ["#3498db", "#95a5a6", "#e74c3c"]):
    sub = enso_temp[enso_temp['ClassNino'] == phase]
    sns.regplot(data=sub, x='Ano', y='Temp_Anomaly', scatter=False, color=color)
plt.axhline(0, linetype="--", color="black", alpha=0.6)
plt.title("Temperature Anomalies by ENSO Phase Over Time\nIs the ENSO signal amplifying as background climate warms?")
plt.xlabel("Year")
plt.ylabel("Temperature Anomaly (°C)")
plt.savefig("Q4_enso_temp_signal.png", dpi=150)
plt.close()

# Correlações com o ONI
oni_corr = climate_data[climate_data['Ano'] >= 1950].dropna(subset=['MeanONI'])
months = range(1, 13)
cor_rain, cor_tmed, cor_tmin = [], [], []
for m in months:
    sub =  oni_corr[oni_corr['Mes'] == m]
    cor_rain.append(sub['MeanONI'].corr(sub['Chuva']))
    cor_tmed.append(sub['MeanONI'].corr(sub['TMED']))
    cor_tmin.append(sub['MeanONI'].corr(sub['TMIN']))

oni_df = pd.DataFrame({'Month': months, 'Cor_Rain': cor_rain, 'Cor_Tmed': cor_tmed, 'Cor_Tmin': cor_tmin})
oni_long = oni_df.melt(id_vars='Month', var_name='Variable', value_name='Correlation')

plt.figure(figsize=(10, 5))
sns.barplot(data=oni_long, x='Month', y='Correlation', hue='Variable', palette='Set1')
plt.axhline(0, color='black', linewidth=0.8)
plt.title("Monthly Correlation Between ONI and Local Climate Variables")
plt.xlabel("Month")
plt.ylabel("Pearson Correlation")
plt.savefig("Q4_oni_correlations.png", dpi=150)
plt.close()

# ==============================================================================
# ITEM 5: ÍNDICES CLIMÁTICOS DE EXTREMOS (SÉRIE SECULAR)
# ==============================================================================

# TR20: Noites Tropicais (Tmin > 20°C)
tr20 = climate_data[climate_data['Ano'] >= 1917].dropna(subset=['TMIN']).groupby('Ano').agg(TR20=('TMIN', lambda x: (x > 20).sum())).reset_index()
plt.figure(figsize=(10, 5))
sns.lineplot(data=tr20, x='Ano', y='TR20', color='#e74c3c', alpha=0.6)
sns.regplot(data=tr20, x='Ano', y='TR20', color='#2c3e50', scatter=False)
plt.title("Tropical Nights (TR20): Days with Tmin > 20°C")
plt.xlabel("Year")
plt.ylabel("Number of Nights")
plt.savefig("Q5_tropical_nights.png", dpi=150)
plt.close()

# CDD: Dias Secos Consecutivos Máximos (Extraído da variável pronta Estiagem)
cdd = climate_data[climate_data['Ano'] >= 1902].groupby('Ano').agg(CDD=('Estiagem', 'max')).reset_index()
plt.figure(figsize=(10, 5))
sns.lineplot(data=cdd, x='Ano', y='CDD', color='#d35400', alpha=0.6)
sns.regplot(data=cdd, x='Ano', y='CDD', color='#c0392b', scatter=False)
plt.title("Consecutive Dry Days (CDD) Index\nMaximum annual dry spell length from Estiagem variable")
plt.xlabel("Year")
plt.ylabel("CDD (days)")
plt.savefig("Q5_CDD.png", dpi=150)
plt.close()

# R95p: Precipitação de dias muito úmidos (> percentil 95 do baseline 1961-1990)
wet_baseline = climate_data[(climate_data['Ano'] >= 1961) & (climate_data['Ano'] <= 1990) & (climate_data['Chuva'] >= 1)]
p95_threshold = wet_baseline['Chuva'].quantile(0.95)

r95p = climate_data[climate_data['Ano'] >= 1902].dropna(subset=['Chuva']).groupby('Ano').agg(
    R95p=('Chuva', lambda x: x[x > p95_threshold].sum())
).reset_index()

plt.figure(figsize=(10, 5))
plt.bar(r95p['Ano'], r95p['R95p'], color='#2980b9', alpha=0.6)
sns.regplot(data=r95p, x='Ano', y='R95p', color='#c0392b', scatter=False, lowess=True)
plt.title("R95p: Total Rainfall from Very Wet Days (> 95th percentile)")
plt.xlabel("Year")
plt.ylabel("R95p (mm)")
plt.savefig("Q5_R95p.png", dpi=150)
plt.close()

# Percentual de Dias Quentes (TX90p) e Noites Quentes (TN90p)
base_warm = climate_data[(climate_data['Ano'] >= 1961) & (climate_data['Ano'] <= 1990)]
tx90_th = base_warm['TMAX'].quantile(0.90)
tn90_th = base_warm['TMIN'].quantile(0.90)

warm_indices = climate_data[climate_data['Ano'] >= 1917].dropna(subset=['TMAX', 'TMIN']).groupby('Ano').agg(
    TX90p=('TMAX', lambda x: (x > tx90_th).sum() / len(x) * 100),
    TN90p=('TMIN', lambda x: (x > tn90_th).sum() / len(x) * 100)
).reset_index()

warm_long = warm_indices.melt(id_vars='Ano', var_name='Index', value_name='Percent')
plt.figure(figsize=(10, 5))
sns.lineplot(data=warm_long, x='Ano', y='Percent', hue='Index', palette={"TX90p": "#e74c3c", "TN90p": "#8e44ad"}, alpha=0.5)
for idx, color in zip(["TX90p", "TN90p"], ["#e74c3c", "#8e44ad"]):
    sns.regplot(data=warm_indices, x='Ano', y=idx, scatter=False, color=color)
plt.axhline(10, linetype="--", color="grey")
plt.title("Warm Days (TX90p) and Warm Nights (TN90p)\nPercentage of days exceeding 90th percentile; dashed line = expected 10%")
plt.xlabel("Year")
plt.ylabel("Percentage (%)")
plt.savefig("Q5_warm_days_nights.png", dpi=150)
plt.close()

# ==============================================================================
# ITEM 6: RADIAÇÃO SOLAR GLOBAL
# ==============================================================================

annual_rad = climate_data[climate_data['Ano'] >= 2000].dropna(subset=['GlobRad']).groupby('Ano').agg(Mean_GlobRad=('GlobRad', 'mean')).reset_index()
plt.figure(figsize=(10, 5))
sns.lineplot(data=annual_rad, x='Ano', y='Mean_GlobRad', color='#f39c12', marker='o')
sns.regplot(data=annual_rad, x='Ano', y='Mean_GlobRad', color='#c0392b')
plt.title("Annual Mean Global Radiation (2000–Present)")
plt.xlabel("Year")
plt.ylabel("Mean Global Radiation (MJ/m²/day)")
plt.savefig("Q6_radiation_trend.png", dpi=150)
plt.close()

# Radiação Sazonal
seasonal_rad = climate_data[climate_data['Ano'] >= 2000].dropna(subset=['GlobRad']).groupby(['Ano', 'Estacao'], observed=False)['GlobRad'].mean().reset_index()
plt.figure(figsize=(10, 5))
sns.lineplot(data=seasonal_rad, x='Ano', y='GlobRad', hue='Estacao')
for est in estacao_order:
    sns.regplot(data=seasonal_rad[seasonal_rad['Estacao'] == est], x='Ano', y='GlobRad', scatter=False)
plt.title("Seasonal Global Radiation Trends")
plt.xlabel("Year")
plt.ylabel("Mean Global Radiation (MJ/m²/day)")
plt.savefig("Q6_seasonal_radiation.png", dpi=150)
plt.close()

# Radiação por Fase ENOS e Estação
rad_enso = climate_data[climate_data['Ano'] >= 2000].dropna(subset=['GlobRad', 'ClassNino']).groupby(['Estacao', 'ClassNino'], observed=False)['GlobRad'].mean().reset_index()
plt.figure(figsize=(10, 6))
sns.barplot(data=rad_enso, x='ClassNino', y='GlobRad', hue='ClassNino', dodge=False, palette={"Strong La Niña": "#3498db", "Intermediate": "#95a5a6", "Strong El Niño": "#e74c3c"})
plt.gca().set_visible(False) # Hack para reaproveitar estrutura via matplotlib em subplots se desejado, aplicando facet manual:
g = sns.catplot(data=rad_enso, x='ClassNino', y='GlobRad', hue='ClassNino', col='Estacao', kind='bar', palette={"Strong La Niña": "#3498db", "Intermediate": "#95a5a6", "Strong El Niño": "#e74c3c"})
g.set_xticklabels(rotation=30)
g.set_axis_labels("ENSO Phase", "Mean Radiation (MJ/m²/day)")
plt.savefig("Q6_radiation_enso.png", dpi=150)
plt.close()

# ==============================================================================
# ITEM 7: EVENTOS COMPOSTOS E PROBABILIDADE DE ANOS CRÍTICOS
# ==============================================================================

compound = climate_data[climate_data['Ano'] >= 1917].dropna(subset=['TMAX']).copy()
compound['Is_Compound'] = (compound['Estiagem'] > 15) & (compound['TMAX'] > 33)
compound_annual = compound.groupby('Ano')['Is_Compound'].sum().reset_index(name='Compound_Days')

plt.figure(figsize=(10, 5))
plt.bar(compound_annual['Ano'], compound_annual['Compound_Days'], color='#8e44ad', alpha=0.7)
sns.regplot(data=compound_annual, x='Ano', y='Compound_Days', color='black', scatter=False, lowess=True)
plt.title("Compound Heat-Drought Days per Year\nDays with Estiagem > 15 AND Tmax > 33°C")
plt.xlabel("Year")
plt.ylabel("Number of Compound Days")
plt.savefig("Q7_compound_events.png", dpi=150)
plt.close()

# Dispersão de Inverno (Temperatura vs Chuva por ENOS)
dry_season = climate_data[(climate_data['Ano'] >= 1950) & (climate_data['Estacao'] == 'Winter')].dropna(subset=['ClassNino'])
dry_season_comp = dry_season.groupby(['Ano', 'ClassNino'], observed=False).agg(
    Mean_TMAX=('TMAX', 'mean'),
    Total_Rain=('Chuva', 'sum')
).reset_index()

plt.figure(figsize=(10, 6))
sns.scatterplot(data=dry_season_comp, x='Total_Rain', y='Mean_TMAX', hue='ClassNino', s=80, alpha=0.7, palette={"Strong La Niña": "#3498db", "Intermediate": "#95a5a6", "Strong El Niño": "#e74c3c"})
plt.title("Winter: Temperature vs Rainfall by ENSO Phase\nLower-right quadrant = hot and dry (highest agricultural risk)")
plt.xlabel("Total Winter Rainfall (mm)")
plt.ylabel("Mean Winter Tmax (°C)")
plt.savefig("Q7_enso_compound_winter.png", dpi=150)
plt.close()

# Probabilidade de Anos Críticos ("Bad Years")
annual_sum = climate_data[climate_data['Ano'] >= 1917].groupby('Ano').agg(Total_Rain=('Chuva', 'sum'), Mean_TMAX=('TMAX', 'mean')).reset_index()
rain_q25 = annual_sum['Total_Rain'].quantile(0.25)
tmax_q75 = annual_sum['Mean_TMAX'].quantile(0.75)
annual_sum['Bad_Year'] = (annual_sum['Total_Rain'] < rain_q25) & (annual_sum['Mean_TMAX'] > tmax_q75)
annual_sum['Decade'] = (annual_sum['Ano'] // 10) * 10

bad_years_dec = annual_sum.groupby('Decade').agg(Pct_Bad=('Bad_Year', lambda x: x.sum() / len(x) * 100)).reset_index()
plt.figure(figsize=(10, 5))
sns.barplot(data=bad_years_dec, x='Decade', y='Pct_Bad', color='#c0392b', alpha=0.7)
plt.title("Probability of a 'Bad Year' by Decade\nBad year = low rainfall (< Q25) AND high Tmax (> Q75)")
plt.xlabel("Decade")
plt.ylabel("Percentage of Bad Years (%)")
plt.savefig("Q7_bad_years.png", dpi=150)
plt.close()

# ==============================================================================
# ITEM 8: ANÁLISE DE RISCO DE INCÊNDIO FLORESTAL (METODOLOGIA DE ANGSTRÖM)
# ==============================================================================

# 1. Cálculo Diário do Índice de Angström e Classificação de Perigo
fire_risk_daily = climate_data[climate_data['Ano'] >= 1917].dropna(subset=['TMAX', 'URMED']).copy()
fire_risk_daily['Angstrom_Index'] = (fire_risk_daily['URMED'] / 20) + ((fire_risk_daily['TMAX'] - 27) / 10)

# Classificação do Risco Florestal
def classe_risco(angstrom):
    if angstrom > 4.0: return "Nulo/Baixo"
    elif angstrom > 2.5: return "Moderado"
    elif angstrom > 2.0: return "Alto"
    else: return "Muito Alto a Extremo"

fire_risk_daily['Classe_Risco'] = fire_risk_daily['Angstrom_Index'].apply(classe_risco)
risk_categories = ["Nulo/Baixo", "Moderado", "Alto", "Muito Alto a Extremo"]
fire_risk_daily['Classe_Risco'] = pd.Categorical(fire_risk_daily['Classe_Risco'], categories=risk_categories, ordered=True)

# 2. Agrupamento Anual para Tendência
fire_risk_annual = fire_risk_daily.groupby('Ano').agg(
    Mean_Angstrom=('Angstrom_Index', 'mean'),
    Days_Critical_Risk=('Angstrom_Index', lambda x: (x <= 2.5).sum())
).reset_index()

print("\n--- Primeiras linhas dos indicadores anuais de Risco de Incêndio ---")
print(fire_risk_annual.head())

# 3. Modelagem Linear e Testes Estatísticos
model_ang = smf.ols('Mean_Angstrom ~ Ano', data=fire_risk_annual).fit()
print(f"\nVariação do índice médio de Angström por década: {model_ang.params['Ano'] * 10:.4f}")

print("\n--- Testes de Mann-Kendall não-paramétricos (Incêndio) ---")
print("Índice de Angström Médio:")
print(trend_summary(fire_risk_annual, 'Ano', 'Mean_Angstrom'))
print("Dias Críticos de Risco de Incêndio (Angström <= 2.5):")
print(trend_summary(fire_risk_annual, 'Ano', 'Days_Critical_Risk'))

# 4. Plotagem Gráfica 8A: Evolução do Número de Dias Críticos por Ano (Salvo como indicado no ggsave e DokuWiki)
plt.figure(figsize=(10, 5))
sns.lineplot(data=fire_risk_annual, x='Ano', y='Days_Critical_Risk', color='#d35400', alpha=0.5)
sns.scatterplot(data=fire_risk_annual, x='Ano', y='Days_Critical_Risk', color='#c0392b', alpha=0.7, s=30)
sns.regplot(data=fire_risk_annual, x='Ano', y='Days_Critical_Risk', color='#2c3e50', scatter=False,
            line_kws={"linewidth": 1.5}, label="Tendência Linear")
plt.title("Evolução do Perigo de Incêndios Florestais em Piracicaba (1917-Presente)\nNúmero anual de dias com Risco Alto a Extremo (Índice de Angström ≤ 2.5)")
plt.xlabel("Ano")
plt.ylabel("Número de Dias Críticos / Ano")
plt.tight_layout()
plt.savefig("Q8_angstrom_filtrado.png", dpi=150) # Nome do arquivo compatível com o DokuWiki fornecido
plt.close()

# 5. Plotagem Gráfica 8B: Sazonalidade Histórica e Impacto do ENSO no Risco
fire_season_enso = fire_risk_daily[fire_risk_daily['Ano'] >= 1950].dropna(subset=['ClassNino'])
fire_season_enso = fire_season_enso.groupby(['Ano', 'Estacao', 'ClassNino'], observed=False).agg(
    Dias_Risco=('Angstrom_Index', lambda x: (x <= 2.5).sum())
).reset_index()

g_fire = sns.catplot(
    data=fire_season_enso, x='ClassNino', y='Dias_Risco', hue='ClassNino', dodge=False,
    col='Estacao', col_wrap=2, kind='box', height=4.5, aspect=1.2,
    palette={"Strong La Niña": "#3498db", "Intermediate": "#95a5a6", "Strong El Niño": "#e74c3c"},
    boxprops=dict(alpha=0.7), flierprops=dict(alpha=0.4)
)
g_fire.set_titles("{col_name}")
g_fire.set_axis_labels("Fase do ENSO", "Dias com Risco Crítico (≤ 2.5)")
g_fire.set_xticklabels(rotation=30)
g_fire.fig.suptitle("Dias Críticos de Incêndio por Estação e Fase do ENSO\nMetodologia Angström aplicada ao monitoramento de Clima Florestal", y=1.02)
plt.savefig("Q8_monte_alegre_trends.png", dpi=150) # Nome mapeado no bloco do ggsave/DokuWiki
plt.close()

print("\nProcessamento completo. Todos os plots de Q1 a Q8 foram gerados com sucesso